name: SpaceONE CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '`vx.y.z-릴리즈` 형태로 버전을 입력해주세요. `vx.y.z`도 가능합니다.'
        required: true
        default: v1.2.3-rc1

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "This is dummy CI3"