name: "[CI] deploy workflows"

on:
  workflow_dispatch:
    inputs:
      group:
        description: '배포할 github_action group을 입력하세요.'
        required: true
      repository:
        description: '[option]특정 repository 지정.'
        required: false
  repository_dispatch:
    types: [deploy_githubaction_workflows]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: set PAT_TOKEN env
        run: echo "PAT_TOKEN=$(echo ${{ secrets.PAT_TOKEN }})" >> $GITHUB_ENV
      - name: deploy
        run: |
          if [ ${{ github.event.inputs.repository }} ];
          then
            python src/main.py --group ${{ github.event.inputs.group }} --repo ${{ github.event.inputs.repository }}
          else
            python src/main.py --group ${{ github.event.inputs.group }}
          fi