name: "[CI] deploy workflows"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: '특정 repository 지정.'
        required: true
      tag:
        description: 'release tag'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: set PAT_TOKEN env
        run: echo "PAT_TOKEN=$(echo ${{ secrets.PAT_TOKEN }})" >> $GITHUB_ENV
      - name: deploy
        run: |
          python src/main.py --repo ${{ github.event.inputs.repository }}

  master_push:
    runs-on: ubuntu-latest
    if: ${{ !github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.event.inputs.repository }}
          event-type: master_push

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.event.inputs.repository }}
          event-type: release
          client-payload: '{"tag": "${{ github.event.inputs.tag }}"}'

